### ISSUE TITLE
ToEnum cannot parse "cross-platform"

### ISSUE THREAD

**Issue by abergs** [abergs/fido2-net-lib#89] opened 2019-04-14 12:03 UTC
The commit https://github.com/abergs/fido2-net-lib/commit/768512a1f864a9d9b555b6ed2ef92f62c4f4b076 introduced a bug which means that the option "cross-platform" cannot be parsed/used.

It throws the exception:
Value 'cross-platform' is not a valid enum name of 'Fido2NetLib.Objects.AuthenticatorAttachment' (ignoreCase=True). Valid values are Platform;CrossPlatform.

Could @CodeTherapist take a look?
Otherwise I suggest we revert that commit

**Comment by aseigler** [comment] 2019-04-14 13:07
I thought this was fixed by #85?

**Comment by aseigler** [comment] 2019-04-14 13:23
We had the same problem with #69 which was fixed by #75.

**Comment by idaviddesmet** [comment] 2019-04-14 20:38
The issue is that it is no longer using the value from EnumMemberAttribute which was fixed in #75 as already mentioned. We could patch the extension and keep the unit tests without reverting. Want me to do it?

**Comment by idaviddesmet** [comment] 2019-04-15 00:07
Had some free time so I created a PR.

At first try, it will try to parse it using enum's TryParse (as it currently does), if it can't it will try using the EnumMember value; if everything fails it collects a list of valid values (properly parsed) and show it in the exception message.

Ex.

```bash
System.ArgumentException: Value 'cross-platforms' is not a valid enum name of 'Fido2NetLib.Objects.AuthenticatorAttachment' (ignoreCase=True). Valid values are: platform, cross-platform.
```
I've added additional tests to complement the ones we already have.

**Comment by CodeTherapist** [comment] 2019-04-15 08:17
@abergs Oh no. Sorry for that - this was never my intension 😢 Maybe we should aim to not have this method anymore and try to convert by deserialization directly to enum as for example #75 does it?

One issue that I see with this method is, that a developers *must* use this method to parse an enum.
It isn't obvious why they couldn't use the [Enum.Parse(...)](https://docs.microsoft.com/en-us/dotnet/api/system.enum.parse?view=netframework-4.7.2#System_Enum_Parse_System_Type_System_String_System_Boolean_) method from the framework. 
That is also why I felt into this trap and thought that we could write it simpler with less code and less complexity.

@idaviddesmet Thanks for the contributions - I will have a look at your PR.

**Closed** 2019-04-24 14:54 UTC
